services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: mailbox-postgres
    environment:
      POSTGRES_DB: mailbox_db
      POSTGRES_USER: mailbox_user
      POSTGRES_PASSWORD: mailbox_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mailbox-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mailbox_user -d mailbox_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Ollama LLM Service
  ollama:
    image: ollama/ollama:latest
    container_name: mailbox-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - mailbox-network
    restart: unless-stopped

  # Python Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mailbox-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://mailbox_user:mailbox_pass@postgres:5432/mailbox_db
      MAILPIT_HOST: mailpit
      MAILPIT_PORT: 8025
      MAILPIT_SMTP_PORT: 1025
      OLLAMA_HOST: ollama
      OLLAMA_PORT: 11434
      OLLAMA_MODEL: phi3
    depends_on:
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_started
      ollama:
        condition: service_started
    volumes:
      - ./backend:/app
    networks:
      - mailbox-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Material Dashboard Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mailbox-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mailbox-network

  # MailPit - Local Mail Server
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailbox-mailpit
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - mailpit_data:/data
    networks:
      - mailbox-network

  # Email Seeder - Generates and sends test emails
  email-seeder:
    build:
      context: ./email-seeder
      dockerfile: Dockerfile
    container_name: mailbox-seeder
    environment:
      MAILPIT_SMTP_HOST: mailpit
      MAILPIT_SMTP_PORT: 1025
      NUM_EMAILS: 2000
      PHISHING_PERCENTAGE: 20
    depends_on:
      - mailpit
    networks:
      - mailbox-network
    command: python seed_emails.py

networks:
  mailbox-network:
    driver: bridge

volumes:
  postgres_data:
  mailpit_data:
  ollama_data:
